name: 📊 Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Every day
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community, repositories
          template: classic
          config_timezone: Asia/Kolkata
          config_animations: true
          config_twemoji: true
